name: chrome_tabs
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  
  assets:
    - fonts/

  fonts:
    - family: Circular
      fonts:
        - asset: fonts/Circular-Book.otf
          weight: 400
        - asset: fonts/Circular-Medium.otf
          weight: 500
        - asset: fonts/Circular-Bold.otf
          weight: 600



